Skyla1:
  LogFilePath: /home/raspberryaoms/Documents/remoteNodeMonitor/logs/skyla1.log

Creed1:
  LogFilePath: /home/raspberryaoms/Documents/remoteNodeMonitor/logs/creed1.log

Skyla2:
  LogFilePath: /home/raspberryaoms/Documents/remoteNodeMonitor/logs/skyla2.log

Creed2:
  LogFilePath: /home/raspberryaoms/Documents/remoteNodeMonitor/logs/creed2.log

GoogleDrive:
  LocalLogPath: /home/raspberryaoms/Documents/remoteNodeMonitor/logs
  RemoteLogPath: ggl-dr:remoteNodeMonitor_logs/logger1/logs

Nucleo:
  Port: '/dev/ttyAMA0'
  Baud: 115200

Programmer:
  Tool: atmelice_updi
  PartID: m4809