Skyla1:
  Molly: True
  Settings:
    DeviceID: 260A2006
    ExternalSensorFreq: 900
    InternalSensorFreq: 900
    StatusFreq: 1800
    CreedTransmitFreq: 3600
    ClearDatalogger: 1
    RTCCTrim: 39
    CreedSettings:
      RadioType: 2
      ConnectionTime: 127
      NoMsgAct: 60
      MsgResp: 10
      MsgRetry: 5
      RadioMode: 0
      LORA_DR: 0
      LORA_CH: 0
      LORA_FQ: 0
      LORA_PLVL: 0
      LTE_SIM: 0
    KeyVault:
      KeysPath: /home/raspberryaoms/Documents/remote_node_monitor/lib/external/flora-keys/vault/aoms_abp.csv

Skyla2:
  Molly: True
  Settings:
    DeviceID: 260A2007
    ExternalSensorFreq: 900
    InternalSensorFreq: 900
    StatusFreq: 1800
    CreedTransmitFreq: 3600
    ClearDatalogger: 1
    RTCCTrim: 39
    CreedSettings:
      RadioType: 2
      ConnectionTime: 127
      NoMsgAct: 60
      MsgResp: 10
      MsgRetry: 5
      RadioMode: 0
      LORA_DR: 0
      LORA_CH: 0
      LORA_FQ: 0
      LORA_PLVL: 0
      LTE_SIM: 0
    KeyVault:
      KeysPath: /home/raspberryaoms/Documents/remote_node_monitor/lib/external/flora-keys/vault/aoms_abp.csv
