Skyla1:
  LogFilePath: /home/raspberryaoms/Documents/remote_node_monitor/logs/skyla1.log

Creed1:
  LogFilePath: /home/raspberryaoms/Documents/remote_node_monitor/logs/creed1.log
  Blues:
    Serial:
      Baud: 115200

Skyla2:
  LogFilePath: /home/raspberryaoms/Documents/remote_node_monitor/logs/skyla2.log

Creed2:
  LogFilePath: /home/raspberryaoms/Documents/remote_node_monitor/logs/creed2.log
  Blues:
    Serial:
      Baud: 115200

DigitalOcean:
  LocalLogPath: /home/raspberryaoms/Documents/remote_node_monitor/logs
  RemoteObserverLogPath: Logs/Observer
  BucketName: "toaster-dev"
  Region: "nyc3"
  Endpoint: "https://nyc3.digitaloceanspaces.com"
  AccessKey: "DO00Y9H4L7NAMCXZBL72"
  SecretAccessKey: "7JD99xkK3TTFdnfTZzBogLmiWqwxRqxSK7zeyRvv1tQ"

Nucleo:
  Port: '/dev/ttyAMA0'
  Baud: 115200

Programmer:
  Tool: atmelice_updi
  PartID: m4809